# 1.16.0
# 1.16.1
# 1.17.0
# 1.18.0

FROM kasmweb/core-ubuntu-noble:1.18.0-rolling-weekly
USER root

ENV HOME=/home/kasm-default-profile
ENV STARTUPDIR=/dockerstartup
ENV INST_DIR=$STARTUPDIR/install
ENV INST_SCRIPTS=/ubuntu/install/zoho_email/install_zoho_email.sh
WORKDIR $HOME

######### Customize Container Here ###########

# Copy install scripts
COPY ./src/ $INST_DIR

# Run installations
RUN \
  for SCRIPT in $INST_SCRIPTS; do \
    bash ${INST_DIR}${SCRIPT} || exit 1; \
  done && \
  $STARTUPDIR/set_user_permission.sh $HOME && \
  rm -f /etc/X11/xinit/Xclients && \
  chown 1000:0 $HOME && \
  mkdir -p /home/kasm-user && \
  chown -R 1000:0 /home/kasm-user && \
  rm -Rf ${INST_DIR}

# Security modifications
COPY ./src/ubuntu/install/misc/single_app_security.sh $INST_SCRIPTS/misc/
RUN  bash $INST_SCRIPTS/misc/single_app_security.sh -t && rm -rf $INST_SCRIPTS/misc/

COPY ./src/ubuntu/install/zoho_email/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh
RUN chmod 755 $STARTUPDIR/custom_startup.sh

# Restrict to single app
COPY ./src/ubuntu/install/misc/restrict_to_single_app.sh $INST_SCRIPTS/misc/
RUN  bash $INST_SCRIPTS/misc/restrict_to_single_app.sh -t && rm -rf $INST_SCRIPTS/misc/


######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME=/home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
