docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-brave-vpn:develop -f dockerfile-kasm-brave-vpn --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-chrome-vpn:develop -f dockerfile-kasm-chrome-vpn --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-chromium-vpn:develop -f dockerfile-kasm-chromium-vpn --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-edge-vpn:develop -f dockerfile-kasm-edge-vpn --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-firefox-vpn:develop -f dockerfile-kasm-firefox-vpn --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-focal-desktop:develop -f dockerfile-kasm-ubuntu-focal-desktop --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-focal-desktop-vpn:develop -f dockerfile-kasm-ubuntu-focal-desktop-vpn --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-focal-developer:develop -f dockerfile-kasm-ubuntu-focal-developer --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-focal-web:develop -f dockerfile-kasm-ubuntu-focal-developer-web --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-focal-backend:develop -f dockerfile-kasm-ubuntu-focal-developer-backend --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-focal-data:develop -f dockerfile-kasm-ubuntu-focal-developer-data --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-focal-docker:develop -f dockerfile-kasm-ubuntu-focal-developer-docker --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-jammy-desktop:develop -f dockerfile-kasm-ubuntu-jammy-desktop --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-jammy-desktop-vpn:develop -f dockerfile-kasm-ubuntu-jammy-desktop-vpn --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-jammy-developer:develop -f dockerfile-kasm-ubuntu-jammy-developer --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-jammy-web:develop -f dockerfile-kasm-ubuntu-jammy-developer-web --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-jammy-backend:develop -f dockerfile-kasm-ubuntu-jammy-developer-backend --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-jammy-data:develop -f dockerfile-kasm-ubuntu-jammy-developer-data --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-jammy-docker:develop -f dockerfile-kasm-ubuntu-jammy-developer-docker --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-noble-desktop:develop -f dockerfile-kasm-ubuntu-noble-desktop --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-noble-desktop-vpn:develop -f dockerfile-kasm-ubuntu-noble-desktop-vpn --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-noble-developer:develop -f dockerfile-kasm-ubuntu-noble-developer --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-noble-web:develop -f dockerfile-kasm-ubuntu-noble-developer-web --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-noble-backend:develop -f dockerfile-kasm-ubuntu-noble-developer-backend --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-noble-data:develop -f dockerfile-kasm-ubuntu-noble-developer-data --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-noble-docker:develop -f dockerfile-kasm-ubuntu-noble-developer-docker --push .
docker buildx build --platform linux/amd64 -t lathanaspa/kasm-zoho-mail:develop -f dockerfile-kasm-zoho-mail --push .