docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-brave-vpn:develop -f dockerfile-kasm-brave-vpn --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-chrome-vpn:develop -f dockerfile-kasm-chrome-vpn --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-edge-vpn:develop -f dockerfile-kasm-edge-vpn --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-firefox-vpn:develop -f dockerfile-kasm-firefox-vpn --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-focal-desktop:develop -f dockerfile-kasm-ubuntu-focal-desktop --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-focal-developer:develop -f dockerfile-kasm-ubuntu-focal-developer --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-focal-desktop-vpn:develop -f dockerfile-kasm-ubuntu-focal-desktop-vpn --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-jammy-desktop:develop -f dockerfile-kasm-ubuntu-jammy-desktop --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-jammy-developer:develop -f dockerfile-kasm-ubuntu-jammy-developer --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-jammy-desktop-vpn:develop -f dockerfile-kasm-ubuntu-jammy-desktop-vpn --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-noble-desktop:develop -f dockerfile-kasm-ubuntu-noble-desktop --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-noble-developer:develop -f dockerfile-kasm-ubuntu-noble-developer --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-noble-desktop-vpn:develop -f dockerfile-kasm-ubuntu-noble-desktop-vpn --push .
docker buildx build --platform linux/amd64 -t lathanaspa/kasm-zoho-mail:develop -f dockerfile-kasm-zoho-mail --push .