docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-focal-developer:develop -f dockerfile-kasm-ubuntu-focal-developer --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-focal-web:develop -f dockerfile-kasm-ubuntu-focal-web --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-focal-backend:develop -f dockerfile-kasm-ubuntu-focal-backend --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-focal-data:develop -f dockerfile-kasm-ubuntu-focal-data --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-focal-docker:develop -f dockerfile-kasm-ubuntu-focal-docker --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-jammy-developer:develop -f dockerfile-kasm-ubuntu-jammy-developer --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-jammy-web:develop -f dockerfile-kasm-ubuntu-jammy-web --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-jammy-backend:develop -f dockerfile-kasm-ubuntu-jammy-backend --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-jammy-data:develop -f dockerfile-kasm-ubuntu-jammy-data --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-jammy-docker:develop -f dockerfile-kasm-ubuntu-jammy-docker --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-noble-developer:develop -f dockerfile-kasm-ubuntu-noble-developer --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-noble-web:develop -f dockerfile-kasm-ubuntu-noble-web --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-noble-backend:develop -f dockerfile-kasm-ubuntu-noble-backend --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-noble-data:develop -f dockerfile-kasm-ubuntu-noble-data --push .
docker buildx build --platform linux/amd64,linux/arm64 -t lathanaspa/kasm-ubuntu-noble-docker:develop -f dockerfile-kasm-ubuntu-noble-docker --push .